### ISSUE TITLE
What is the wiring for this sensor?

### ISSUE THREAD

**Issue by joshagirgis** [dzalf/LM95071_Temperature_Sensor#2]
Do I need a 10k resistor between the MISO and MOSI pins, for bidirectionality?

**Comment by dzalf** [comment]
Hi

Sorry for the late reply.

Yes, please refer to page 1 and 3 from the [datasheet](http://www.ti.com/lit/ds/snis137g/snis137g.pdf?&ts=1589683860735) where it indicates that you can use a 10k resistor for bidirectionality.

In case you would like to prototype with this sensor, check [this](https://www.tindie.com/products/ivorycircuits/lm95071-spimw-temperature-sensor-breakout-board/) out

Cheers

dzalf

**Comment by joshagirgis** [comment]
No worries. I've found that the best way to do it is to bit bang and mimic a SPI port to achieve bidirectionality. Was pretty easy to implement. Bridging a 10k isn't a great solution if one is to use the SPI port with other sensors.

**Comment by dzalf** [comment]
Indeed. I actually ran into some issues when testing my library with an SPI Graphic Screen. 

I think there was some sort of obfuscation on the communication as the screen uses a different clock and data frame structure. Weird.

Glad you could solve it. I might go back and test it as you did.

Stay safe ;)
